# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63588c7aaa640bdd92e0e12c952aa2caeb04c8f3deb7382bb7eee9d53626048aaffe5812785d3549c72218cb8a67c6813c18b26fb1ca1f38fbba8eb363b2be04

test:
  secret_key_base: b1360bf3ec96f0faf7273b335c0ecc61581228f81602450618c87de8422593b17efa086c460e136174ea8a7e0597b216089e7dc5b6b0efe7dac381d1f0122fc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
